### ISSUE TITLE
Can you add image dimensions to the objects?

### ISSUE THREAD

**Issue by iclanzan** [akoenig/imacss#6]
I have icons of different widths that I want to use next to text and in order to do that I would need to add the appropriate padding to the elements.

**Comment by akoenig** [comment]
hey @iclanzan - you can add the respective padding to your icons by writing an own customized function. See ["Passing a function to customize the resulting CSS rule set"](https://github.com/akoenig/imacss#passing-a-function-to-customize-the-resulting-css-rule-set) for more information.

**Comment by iclanzan** [comment]
Hi @akoenig and thanks for the reply. I know I can do that, but in my case images are of different sizes so that solution does not help.

**Comment by akoenig** [comment]
@iclanzan Ah okay, I understand. You have to create separate selectors for each of your icon with the individual padding / margin. Your browser should merge both selectors then (the one from the generated css and your individual selector):

```css
.imacss.imacss-quitter {
    padding-left: 2em;
}
```

**Comment by iclanzan** [comment]
Exactly!

—
Sorin Iclanzan
http://SongPane.com

**Comment by iclanzan** [comment]
So what’s the conclusion? Will you implement a solution to this?

**Comment by akoenig** [comment]
@iclanzan I guess that no implementation work is necessary. You can add your margin / padding by extending the generated selectors individually (straight in the CSS).

**Comment by iclanzan** [comment]
@akoenig I don’t want to hardcode the values. It would be nice to take those dimensions from the SVG files themselves.

Anyway, I implemented my own solution in the form of a [new lib](https://github.com/RealGeeks/svgcss).
